language: android

android:
  components:
    - build-tools-21.1.2
    - android-21

    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

jdk:
  - oraclejdk7

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2

script:
    ./gradlew assembleDebug
